#include "RNOH/PackageProvider.h"
#include "ClipboardPackage.h"
#include "FPFileAccessPackage.h"
#include "FPStaticServerPackage.h"
#include "RNOHPackagesFactory.h"
#include "RNCNetInfoPackage.h"
#include "SafeAreaViewPackage.h"
#include "generated/RNOHGeneratedPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<ClipboardPackage>(ctx));
  packages.push_back(std::make_shared<RNCNetInfoPackage>(ctx));
  packages.push_back(std::make_shared<SafeAreaViewPackage>(ctx));
  packages.push_back(std::make_shared<FPFileAccessPackage>(ctx));
  packages.push_back(std::make_shared<FPStaticServerPackage>(ctx));
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(
      ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  return packages;
}
