import { StyleSheet } from 'react-native';

import { theme } from './theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
    position: 'relative',
  },
  screenRoot: {
    flex: 1,
    position: 'relative',
  },
  loadingShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingTitle: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  page: {
    paddingBottom: 32,
    paddingTop: 4,
  },
  readyShell: {
    flex: 1,
  },
  noticeOverlay: {
    bottom: 74,
    elevation: 24,
    position: 'absolute',
    shadowColor: theme.colors.shadowStrong,
    shadowOffset: {
      height: 12,
      width: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    zIndex: 32,
  },
  screenSection: {
    flex: 1,
    minHeight: 0,
  },
  screenHeaderShell: {
    backgroundColor: theme.colors.headerSurface,
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
    paddingBottom: theme.tokens.spacing.sm + 2,
    paddingTop: theme.tokens.spacing.xs,
    ...theme.tokens.shadow.subtle,
    zIndex: 6,
  },
  settingsHeaderShell: {
    paddingBottom: 6,
  },
  screenScroll: {
    flex: 1,
  },
  settingsPage: {
    gap: 16,
  },
  globalTopBar: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 6,
    minHeight: 36,
  },
  globalTopBarStacked: {
    justifyContent: 'space-between',
  },
  globalTopBarActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  settingsTopBar: {
    alignItems: 'flex-end',
    minHeight: 36,
  },
  localeMenuAnchor: {
    borderRadius: theme.radius.pill,
  },
  localeMenuItemActiveLabel: {
    color: theme.colors.primaryStrong,
    fontWeight: '800',
  },
  settingsHeroCard: {
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  settingsTitle: {
    color: theme.colors.ink,
    fontSize: 28,
    fontWeight: '800',
  },
  settingsSubtitle: {
    color: theme.colors.inkSoft,
    fontSize: 14,
    lineHeight: 22,
  },
  settingsCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderWidth: 1,
    gap: theme.tokens.spacing.md - 2,
    padding: theme.tokens.spacing.md + 2,
    ...theme.tokens.shadow.card,
  },
  settingsSectionLabel: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  settingsRow: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.tokens.radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.tokens.spacing.md - 4,
    justifyContent: 'space-between',
    paddingHorizontal: theme.tokens.spacing.md,
    paddingVertical: theme.tokens.spacing.md,
    ...theme.tokens.shadow.subtle,
  },
  settingsRowLead: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  settingsIconWrap: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    shadowColor: theme.colors.primaryShadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.22,
    shadowRadius: 12,
    width: 42,
  },
  settingsIcon: {
    color: theme.colors.primaryStrong,
    fontSize: 14,
    fontWeight: '800',
  },
  settingsRowText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  settingsRowTitle: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  settingsRowDescription: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsRowValue: {
    color: theme.colors.ink,
    fontSize: 13,
    fontWeight: '700',
    maxWidth: '34%',
    textAlign: 'right',
  },
  settingsHint: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  segmentedTabBar: {
    backgroundColor: theme.colors.tabSurface,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    paddingHorizontal: theme.tokens.spacing.md - 4,
    paddingTop: theme.tokens.spacing.sm - 2,
    ...theme.tokens.shadow.floating,
  },
  segmentedTabs: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.tokens.radius.lg,
    borderWidth: 1,
    padding: theme.tokens.spacing.xs,
    width: '100%',
  },
  segmentedTabButton: {
    borderColor: 'transparent',
  },
  segmentedTabLabel: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  segmentedTabGlyph: {
    fontWeight: '800',
    lineHeight: 18,
    marginTop: -1,
    textAlign: 'center',
  },
  bottomTabBar: {
    alignItems: 'center',
    backgroundColor: theme.colors.tabSurface,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  helpTargetWrap: {
    borderRadius: theme.radius.pill,
  },
  sidebarPanel: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderWidth: 1,
    elevation: 8,
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: theme.colors.shadowStrong,
    shadowOffset: {
      height: 14,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 18,
  },
  sidebarListCard: {
    gap: 12,
  },
  sidebarHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  sidebarHeader: {
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  sidebarSectionTitle: {
    color: theme.colors.ink,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  sidebarSectionMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  projectDrawerSection: {
    marginHorizontal: 0,
    marginVertical: 0,
  },
  projectHistoryRow: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: 20,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    minHeight: 64,
    paddingHorizontal: 8,
    paddingVertical: 8,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  projectHistoryRowActive: {
    backgroundColor: theme.colors.primarySoft,
    borderLeftColor: theme.colors.primaryStrong,
    borderLeftWidth: 3,
    borderColor: theme.colors.primary,
    elevation: 4,
    paddingLeft: 10,
    shadowColor: theme.colors.primaryShadow,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  projectHistoryRowDivider: {
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
  },
  projectHistoryRowBody: {
    flex: 1,
    gap: 8,
    minWidth: 0,
    paddingVertical: 4,
  },
  projectHistoryRowHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  projectHistoryRowTitle: {
    color: theme.colors.ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 0,
  },
  projectHistoryRowTitleActive: {
    color: theme.colors.ink,
  },
  projectHistoryRowDate: {
    color: theme.colors.inkMuted,
    fontSize: 11,
    lineHeight: 18,
  },
  projectHistoryRowMetaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  projectHistoryRowMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  projectHistoryRowMetaActive: {
    color: theme.colors.ink,
  },
  projectHistoryMenuDeleteLabel: {
    color: theme.colors.dangerStrong,
  },
  main: {
    flex: 1,
    minWidth: 0,
    gap: 16,
  },
  mainStartup: {
    justifyContent: 'center',
    minHeight: 540,
  },
  mainContent: {
    gap: 0,
  },
  sidebarOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  sidebarBackdrop: {
    backgroundColor: theme.colors.backdrop,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  dialogOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 30,
  },
  dialogBackdrop: {
    backgroundColor: theme.colors.backdrop,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  renameDialogPanel: {
    gap: 14,
    marginHorizontal: 20,
    maxWidth: 420,
    padding: 18,
    width: '100%',
  },
  renameDialogTitle: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  renameDialogInput: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    color: theme.colors.ink,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  renameDialogActions: {
    flexDirection: 'row',
    gap: 10,
  },
  renameDialogActionCell: {
    flex: 1,
    minWidth: 0,
  },
  sidebarDrawerPanel: {
    backgroundColor: theme.colors.background,
    borderColor: theme.colors.border,
    borderRightWidth: 1,
    bottom: 0,
    left: 0,
    paddingTop: 12,
    position: 'absolute',
    top: 0,
  },
  sidebarDrawerScrollContent: {
    gap: 0,
    paddingBottom: 24,
  },
  summaryShell: {
    backgroundColor: theme.colors.headerSurface,
    borderColor: theme.colors.border,
    elevation: 12,
    gap: 14,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingVertical: 20,
    position: 'relative',
    shadowColor: theme.colors.shadowStrong,
    shadowOffset: {
      height: 18,
      width: 0,
    },
    shadowOpacity: 0.24,
    shadowRadius: 24,
  },
  summaryShellCompact: {
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  headerMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  headerTitle: {
    color: theme.colors.ink,
    fontSize: 32,
    fontWeight: '800',
  },
  headerTitleCompact: {
    fontSize: 28,
  },
  headerMeta: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    color: theme.colors.ink,
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    maxWidth: '58%',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 9,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 6,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    textAlign: 'right',
  },
  metricRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  metricRowCompact: {
    gap: 8,
  },
  infoBadge: {
    alignItems: 'center',
    flexBasis: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 62,
    minWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 4,
  },
  infoBadgeCompact: {
    flexDirection: 'column',
    gap: 6,
    minHeight: 86,
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  infoBadgeIconWrap: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.highlight,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 3,
    flexShrink: 0,
    height: 54,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: theme.colors.primaryShadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    width: 54,
  },
  infoBadgeIconWrapCompact: {
    borderRadius: 16,
    height: 48,
    width: 48,
  },
  infoBadgeText: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  infoBadgeTextCompact: {
    alignItems: 'center',
    alignSelf: 'center',
    flex: 0,
    gap: 3,
    maxWidth: '100%',
    minWidth: 0,
  },
  infoBadgeLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  infoBadgeLabelCompact: {
    fontSize: 10,
    lineHeight: 13,
    textAlign: 'center',
  },
  infoBadgeValue: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  infoBadgeValueCompact: {
    fontSize: 16,
    lineHeight: 18,
    textAlign: 'center',
  },
  quickToolsTitle: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  topGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
  },
  topGridCompact: {
    flexDirection: 'column',
  },
  card: {
    backgroundColor: theme.colors.panelWarm,
    borderColor: theme.colors.border,
    borderWidth: 1,
    flex: 1,
    borderRadius: theme.radius.card,
    gap: theme.tokens.spacing.md,
    padding: theme.tokens.spacing.lg - 4,
    ...theme.tokens.shadow.card,
  },
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: theme.colors.ink,
    fontSize: 20,
    fontWeight: '800',
  },
  stepEyebrow: {
    color: theme.colors.primaryStrong,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  phaseSummaryText: {
    color: theme.colors.inkSoft,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 4,
  },
  statusChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.mintSoft,
    borderRadius: theme.radius.pill,
    borderColor: theme.colors.success,
    borderWidth: 1,
    elevation: 2,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 7,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  statusDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusChipText: {
    color: theme.colors.ink,
    fontWeight: '700',
  },
  topGridTourTarget: {
    alignSelf: 'stretch',
    flex: 1,
    minWidth: 0,
  },
  startupTourTarget: {
    alignSelf: 'center',
    maxWidth: 620,
    width: '100%',
  },
  projectTourTarget: {
    alignSelf: 'stretch',
  },
  contentWorkspaceTourTarget: {
    alignSelf: 'stretch',
    flex: 1.4,
    minWidth: 0,
  },
  serviceHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    width: '100%',
  },
  serviceHeaderTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  networkTag: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    elevation: 3,
    flexDirection: 'row',
    flexShrink: 1,
    gap: 6,
    maxWidth: '100%',
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  networkTagWarning: {
    backgroundColor: theme.colors.warningSoft,
    borderColor: theme.colors.warning,
  },
  networkTagLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  networkTagValue: {
    color: theme.colors.ink,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    minWidth: 0,
  },
  serviceAddressSection: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  serviceAddressActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  serviceAddressTarget: {
    borderRadius: 20,
  },
  serviceAddressCollapsed: {
    alignItems: 'flex-start',
    backgroundColor: theme.colors.skySoft,
    borderColor: theme.colors.primary,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 4,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 14,
  },
  serviceAddressCollapsedLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  serviceAddressCollapsedValue: {
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  keyValueTile: {
    flex: 1,
    minWidth: 0,
    borderRadius: 18,
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderWidth: 1,
    elevation: 4,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 14,
  },
  keyLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  keyValue: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  keyValueTileFill: {
    alignSelf: 'stretch',
    flex: 1,
    width: 'auto',
  },
  securityModeSwitchText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  securityModeTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 2,
  },
  securityModeSwitchTitle: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  serviceCard: {
    overflow: 'hidden',
    zIndex: 2,
  },
  serviceStartupCard: {
    alignSelf: 'center',
    gap: 16,
    paddingHorizontal: 22,
    paddingVertical: 22,
    width: '100%',
  },
  serviceStartupFocusCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    justifyContent: 'space-between',
    minHeight: 400,
  },
  serviceSummaryCard: {
    flex: 0.82,
    gap: 14,
  },
  startupHero: {
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  startupNetworkRow: {
    alignItems: 'flex-end',
    alignSelf: 'stretch',
  },
  startupButtonStage: {
    alignItems: 'center',
    height: 232,
    justifyContent: 'center',
    position: 'relative',
    width: 232,
  },
  startupHalo: {
    backgroundColor: 'rgba(0, 122, 255, 0.14)',
    borderRadius: 116,
    height: 232,
    position: 'absolute',
    width: 232,
  },
  startupHaloOuter: {
    backgroundColor: 'rgba(0, 122, 255, 0.06)',
    borderColor: 'rgba(0, 122, 255, 0.22)',
    borderRadius: 104,
    borderWidth: 1,
    height: 208,
    position: 'absolute',
    width: 208,
  },
  startupCircle: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: theme.colors.primary,
    borderColor: 'rgba(255,255,255,0.58)',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 18,
    shadowColor: theme.colors.primaryShadow,
    shadowOffset: {
      height: 18,
      width: 0,
    },
    shadowOpacity: 0.48,
    shadowRadius: 26,
    width: 184,
  },
  startupCircleBusy: {
    backgroundColor: theme.colors.primaryStrong,
    opacity: 0.82,
  },
  startupCircleWarning: {
    backgroundColor: theme.colors.danger,
    borderColor: theme.colors.dangerSoft,
    shadowColor: 'rgba(255, 59, 48, 0.24)',
  },
  startupCircleShine: {
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 88,
    height: 92,
    left: 20,
    position: 'absolute',
    top: 16,
    transform: [{ rotate: '-18deg' }],
    width: 142,
  },
  startupCircleOrbit: {
    borderColor: 'rgba(255, 255, 255, 0.34)',
    borderRadius: 75,
    borderWidth: 1,
    height: 150,
    position: 'absolute',
    transform: [{ rotate: '28deg' }],
    width: 150,
  },
  startupCircleKicker: {
    color: theme.colors.inkOnStrongSoft,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
    textAlign: 'center',
  },
  startupCircleLabel: {
    color: theme.colors.inkOnStrong,
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 30,
    textAlign: 'center',
  },
  startupStatusText: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
    maxWidth: 520,
    textAlign: 'center',
  },
  startupSuggestionText: {
    color: theme.colors.warningStrong,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
    maxWidth: 520,
    textAlign: 'center',
  },
  startupPreviewGrid: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  stepPreviewTile: {
    backgroundColor: theme.colors.surfaceGlassTint,
    borderColor: theme.colors.borderStrong,
    borderRadius: 18,
    borderWidth: 1,
    elevation: 3,
    flex: 1,
    gap: 5,
    minWidth: 180,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  stepPreviewLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '800',
  },
  stepPreviewValue: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 20,
  },
  runningServiceGrid: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  runningServiceControls: {
    flex: 1,
    gap: 12,
    minWidth: 220,
  },
  serviceSecondaryPanel: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 20,
    borderWidth: 1,
    elevation: 4,
    gap: 12,
    padding: 14,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 14,
  },
  serviceSecondaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  qrPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    elevation: 4,
    justifyContent: 'center',
    maxWidth: '100%',
    overflow: 'hidden',
    padding: 16,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 10,
      width: 0,
    },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    width: '100%',
    zIndex: 3,
  },
  sharedFilesCard: {
    gap: 12,
  },
  contentWorkspaceCard: {
    alignSelf: 'stretch',
    gap: theme.tokens.spacing.md - 4,
    minWidth: 0,
  },
  contentWorkspaceMotion: {
    alignSelf: 'stretch',
    flex: 1.4,
    minWidth: 0,
  },
  contentWorkspaceHeader: {
    alignItems: 'flex-start',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  contentWorkspaceHeaderMain: {
    flex: 1,
    gap: 4,
    minWidth: 220,
  },
  contentWorkspaceMeta: {
    color: theme.colors.inkSoft,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  contentServiceTarget: {
    alignSelf: 'stretch',
  },
  contentServiceAccessStack: {
    alignSelf: 'stretch',
    gap: 10,
  },
  contentServiceStrip: {
    alignItems: 'stretch',
    backgroundColor: theme.colors.skySoft,
    borderColor: theme.colors.primary,
    borderRadius: theme.tokens.radius.lg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.tokens.spacing.sm,
    minHeight: 96,
    paddingHorizontal: theme.tokens.spacing.sm + 2,
    paddingVertical: theme.tokens.spacing.sm,
    ...theme.tokens.shadow.subtle,
  },
  contentServiceStopCell: {
    alignSelf: 'stretch',
    flexShrink: 0,
    width: 78,
  },
  contentServiceStopButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.dangerSoft,
    borderColor: theme.colors.danger,
    borderWidth: 1,
    borderRadius: 16,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 6,
    ...theme.tokens.shadow.action,
  },
  contentServiceStopPressed: {
    opacity: 0.82,
  },
  contentServiceStopDisabled: {
    opacity: 0.5,
  },
  contentServiceStopLabel: {
    color: theme.colors.dangerStrong,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 18,
    textAlign: 'center',
  },
  contentServiceAddress: {
    alignSelf: 'center',
    color: theme.colors.inkSoft,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    minWidth: 0,
  },
  contentServiceQrFrame: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    height: 180,
    justifyContent: 'center',
    padding: 6,
    width: 180,
  },
  contentServiceQrPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.tokens.radius.lg,
    borderWidth: 1,
    justifyContent: 'center',
    paddingVertical: 14,
    ...theme.tokens.shadow.subtle,
  },
  contentServiceActions: {
    alignItems: 'center',
    flexDirection: 'column',
    flexShrink: 0,
    gap: 6,
    justifyContent: 'center',
  },
  contentWorkspaceSections: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 12,
  },
  contentWorkspaceSectionsCompact: {
    flexDirection: 'column',
    gap: 18,
  },
  contentWorkspaceSection: {
    alignSelf: 'stretch',
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  contentWorkspacePrimary: {
    backgroundColor: theme.colors.surfaceGlassTint,
    borderColor: theme.colors.border,
    flex: 0.9,
  },
  contentWorkspaceSecondary: {
    backgroundColor: theme.colors.surfaceGlassTint,
    borderColor: theme.colors.border,
    flex: 1.2,
  },
  contentWorkspaceSecondarySeparated: {
    borderLeftColor: theme.colors.border,
    borderLeftWidth: 1,
    paddingLeft: 12,
  },
  contentSectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  contentSectionMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  sharedFilesHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  sharedHeaderActionButton: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
    borderWidth: 1,
    minWidth: 82,
  },
  sharedSelectionToolbar: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    padding: theme.tokens.spacing.md - 4,
  },
  sharedSelectionActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sharedSelectionCount: {
    color: theme.colors.inkSoft,
    fontSize: 13,
    fontWeight: '800',
  },
  activeProjectHeaderMain: {
    gap: 4,
  },
  activeProjectTitle: {
    color: theme.colors.ink,
    fontSize: 24,
    fontWeight: '800',
  },
  activeProjectMeta: {
    color: theme.colors.inkSoft,
    lineHeight: 20,
  },
  projectContentGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
  },
  projectContentGridCompact: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  subsection: {
    alignSelf: 'stretch',
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  subsectionTitle: {
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  messageCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderWidth: 1,
    elevation: 3,
    gap: 10,
    padding: 16,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  messageBody: {
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  messageMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
  },
  fileCard: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderWidth: 1,
    elevation: 3,
    gap: 12,
    padding: 16,
    shadowColor: theme.colors.shadow,
    shadowOffset: {
      height: 8,
      width: 0,
    },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  sharedFileCardSelected: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  fileCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  fileCardHeaderCompact: {
    flexDirection: 'column',
  },
  fileCardHeaderMain: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  sharedSelectionBox: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 8,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  sharedSelectionBoxSelected: {
    backgroundColor: theme.colors.primaryStrong,
    borderColor: theme.colors.primaryStrong,
  },
  sharedSelectionBoxLabel: {
    color: theme.colors.inkMuted,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 18,
  },
  sharedSelectionBoxLabelSelected: {
    color: theme.colors.inkOnStrong,
  },
  fileName: {
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  fileMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  fileReceivedAt: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  fileInlineMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  fileTag: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.pill,
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '800',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  fileTagShared: {
    backgroundColor: theme.colors.mintSoft,
    color: theme.colors.mint,
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  fileCardActionsStack: {
    gap: 8,
  },
  fileCardActionsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
  },
  fileCardActionCell: {
    flex: 1,
    minWidth: 0,
  },
});
