import {StyleSheet} from 'react-native';

import {theme} from './theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
    position: 'relative',
  },
  screenRoot: {
    flex: 1,
    position: 'relative',
  },
  backdropLayer: {
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  backdropGlow: {
    borderRadius: 999,
    position: 'absolute',
  },
  backdropGlowPrimary: {
    backgroundColor: theme.colors.primarySoft,
    height: 260,
    opacity: 0.9,
    right: -40,
    top: -36,
    width: 260,
  },
  backdropGlowSecondary: {
    backgroundColor: theme.colors.surfaceTint,
    bottom: 80,
    height: 220,
    left: -60,
    opacity: 0.75,
    width: 220,
  },
  loadingShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingTitle: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  page: {
    paddingBottom: 32,
    paddingTop: 4,
  },
  readyShell: {
    flex: 1,
  },
  screenSection: {
    flex: 1,
    minHeight: 0,
  },
  screenHeaderShell: {
    backgroundColor: theme.colors.background,
    paddingBottom: 8,
    paddingTop: 4,
    zIndex: 2,
  },
  settingsHeaderShell: {
    paddingBottom: 6,
  },
  screenScroll: {
    flex: 1,
  },
  settingsPage: {
    gap: 16,
  },
  globalTopBar: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 6,
    minHeight: 36,
  },
  globalTopBarStacked: {
    justifyContent: 'space-between',
  },
  globalTopBarActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  settingsTopBar: {
    alignItems: 'flex-end',
    minHeight: 36,
  },
  localeMenuAnchor: {
    borderRadius: theme.radius.pill,
  },
  localeMenuItemActiveLabel: {
    color: theme.colors.primaryStrong,
    fontWeight: '800',
  },
  settingsHeroCard: {
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  settingsTitle: {
    color: theme.colors.ink,
    fontSize: 28,
    fontWeight: '800',
  },
  settingsSubtitle: {
    color: theme.colors.inkSoft,
    fontSize: 14,
    lineHeight: 22,
  },
  settingsCard: {
    gap: 14,
    padding: 18,
  },
  settingsSectionLabel: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  settingsRow: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  settingsRowLead: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  settingsIconWrap: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 18,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  settingsIcon: {
    color: theme.colors.primaryStrong,
    fontSize: 14,
    fontWeight: '800',
  },
  settingsRowText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  settingsRowTitle: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  settingsRowDescription: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  settingsRowValue: {
    color: theme.colors.ink,
    fontSize: 13,
    fontWeight: '700',
    maxWidth: '34%',
    textAlign: 'right',
  },
  settingsHint: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  segmentedTabBar: {
    backgroundColor: theme.colors.overlay,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  segmentedTabs: {
    width: '100%',
  },
  segmentedTabGlyph: {
    fontWeight: '800',
    lineHeight: 18,
    marginTop: -1,
    textAlign: 'center',
  },
  bottomTabBar: {
    alignItems: 'center',
    backgroundColor: theme.colors.overlay,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  helpTargetWrap: {
    borderRadius: theme.radius.pill,
  },
  sidebarPanel: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  sidebarListCard: {
    gap: 12,
  },
  sidebarHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  sidebarHeader: {
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  sidebarSectionTitle: {
    color: theme.colors.ink,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  sidebarSectionMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  projectDrawerSection: {
    marginHorizontal: 0,
    marginVertical: 0,
  },
  projectHistoryRow: {
    alignItems: 'center',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 8,
    minHeight: 64,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  projectHistoryRowActive: {
    backgroundColor: theme.colors.primarySoft,
    borderLeftColor: theme.colors.primaryStrong,
    borderLeftWidth: 3,
    paddingLeft: 10,
  },
  projectHistoryRowDivider: {
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
  },
  projectHistoryRowBody: {
    flex: 1,
    gap: 8,
    minWidth: 0,
    paddingVertical: 4,
  },
  projectHistoryRowHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  projectHistoryRowTitle: {
    color: theme.colors.ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 0,
  },
  projectHistoryRowTitleActive: {
    color: theme.colors.ink,
  },
  projectHistoryRowDate: {
    color: theme.colors.inkMuted,
    fontSize: 11,
    lineHeight: 18,
  },
  projectHistoryRowMetaWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  projectHistoryRowMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  projectHistoryRowMetaActive: {
    color: theme.colors.ink,
  },
  projectHistoryMenuDeleteLabel: {
    color: theme.colors.dangerStrong,
  },
  main: {
    flex: 1,
    minWidth: 0,
    gap: 16,
  },
  sidebarOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  sidebarBackdrop: {
    backgroundColor: theme.colors.backdrop,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  dialogOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 30,
  },
  dialogBackdrop: {
    backgroundColor: theme.colors.backdrop,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  renameDialogPanel: {
    gap: 14,
    marginHorizontal: 20,
    maxWidth: 420,
    padding: 18,
    width: '100%',
  },
  renameDialogTitle: {
    color: theme.colors.ink,
    fontSize: 18,
    fontWeight: '800',
  },
  renameDialogInput: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 16,
    borderWidth: 1,
    color: theme.colors.ink,
    fontSize: 15,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  renameDialogActions: {
    flexDirection: 'row',
    gap: 10,
  },
  renameDialogActionCell: {
    flex: 1,
    minWidth: 0,
  },
  sidebarDrawerPanel: {
    backgroundColor: theme.colors.background,
    borderColor: theme.colors.border,
    borderRightWidth: 1,
    bottom: 0,
    left: 0,
    paddingTop: 12,
    position: 'absolute',
    top: 0,
  },
  sidebarDrawerScrollContent: {
    gap: 0,
    paddingBottom: 24,
  },
  summaryShell: {
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  headerMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  headerTitle: {
    color: theme.colors.ink,
    fontSize: 32,
    fontWeight: '800',
  },
  headerTitleCompact: {
    fontSize: 28,
  },
  headerMeta: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    color: theme.colors.ink,
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '700',
    maxWidth: '58%',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 8,
    textAlign: 'right',
  },
  metricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  infoBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  infoBadgeSuccess: {
    backgroundColor: theme.colors.successSoft,
    borderRadius: theme.radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  infoBadgeIcon: {
    color: theme.colors.primaryStrong,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 16,
  },
  infoBadgeText: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minWidth: 0,
  },
  infoBadgeLabel: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  infoBadgeValue: {
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  quickToolsTitle: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  topGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
  },
  topGridCompact: {
    flexDirection: 'column',
  },
  card: {
    flex: 1,
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.card,
    gap: 14,
    padding: 18,
  },
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: theme.colors.ink,
    fontSize: 20,
    fontWeight: '800',
  },
  statusChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.surfaceElevated,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  statusDot: {
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusChipText: {
    color: theme.colors.ink,
    fontWeight: '700',
  },
  topGridTourTarget: {
    alignSelf: 'stretch',
    flex: 1,
    minWidth: 0,
  },
  projectTourTarget: {
    alignSelf: 'stretch',
  },
  serviceHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
    width: '100%',
  },
  serviceHeaderTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  networkTag: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: theme.colors.secondarySoft,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 1,
    gap: 6,
    maxWidth: '56%',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  networkTagWarning: {
    backgroundColor: theme.colors.warningSoft,
    borderColor: theme.colors.warning,
  },
  networkTagLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  networkTagValue: {
    color: theme.colors.ink,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
    minWidth: 0,
  },
  serviceAddressSection: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 10,
    width: '100%',
  },
  serviceAddressActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  serviceAddressTarget: {
    borderRadius: 20,
  },
  serviceAddressCollapsed: {
    alignItems: 'flex-start',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  serviceAddressCollapsedLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  serviceAddressCollapsedValue: {
    color: theme.colors.ink,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  keyValueTile: {
    flex: 1,
    minWidth: 0,
    borderRadius: 18,
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderWidth: 1,
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  keyLabel: {
    color: theme.colors.inkSoft,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  keyValue: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
  },
  keyValueTileFill: {
    alignSelf: 'stretch',
    flex: 1,
    width: 'auto',
  },
  securityModeSwitchText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  securityModeTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 2,
  },
  securityModeSwitchTitle: {
    color: theme.colors.ink,
    fontSize: 15,
    fontWeight: '700',
  },
  serviceCard: {
    overflow: 'hidden',
    zIndex: 2,
  },
  serviceSecondaryPanel: {
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  serviceSecondaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  qrPanel: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: theme.colors.surfaceMuted,
    borderColor: theme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    justifyContent: 'center',
    maxWidth: '100%',
    overflow: 'hidden',
    padding: 16,
    width: '100%',
    zIndex: 3,
  },
  sharedFilesCard: {
    gap: 12,
  },
  sharedFilesHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  activeProjectHeaderMain: {
    gap: 4,
  },
  activeProjectTitle: {
    color: theme.colors.ink,
    fontSize: 24,
    fontWeight: '800',
  },
  activeProjectMeta: {
    color: theme.colors.inkSoft,
    lineHeight: 20,
  },
  projectContentGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
  },
  projectContentGridCompact: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  subsection: {
    alignSelf: 'stretch',
    flex: 1,
    gap: 10,
  },
  subsectionTitle: {
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  messageCard: {
    gap: 10,
    padding: 16,
  },
  messageBody: {
    color: theme.colors.ink,
    fontSize: 15,
    lineHeight: 22,
  },
  messageMeta: {
    color: theme.colors.inkSoft,
    fontSize: 12,
  },
  fileCard: {
    gap: 12,
    padding: 16,
  },
  fileCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  fileCardHeaderCompact: {
    flexDirection: 'column',
  },
  fileCardHeaderMain: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  fileName: {
    color: theme.colors.ink,
    fontSize: 16,
    fontWeight: '800',
  },
  fileMeta: {
    color: theme.colors.inkSoft,
    lineHeight: 20,
  },
  fileReceivedAt: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  filePath: {
    color: theme.colors.inkSoft,
    fontSize: 12,
    lineHeight: 18,
  },
  fileTag: {
    alignSelf: 'flex-start',
    backgroundColor: theme.colors.surfaceMuted,
    borderRadius: theme.radius.pill,
    color: theme.colors.inkSoft,
    fontSize: 12,
    fontWeight: '800',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  fileTagShared: {
    color: theme.colors.primaryStrong,
  },
  inlineActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  fileCardActionsRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 8,
  },
  fileCardActionsRowCompact: {
    flexDirection: 'column',
  },
  fileCardActionCell: {
    flex: 1,
    minWidth: 0,
  },
});
