import { appColors } from './colors';
import { appTokens } from './tokens';

export const USE_REDESIGNED_UI = true;

export const theme = {
  colors: {
    background: appColors.background,
    surface: appColors.surface,
    surfaceElevated: appColors.surfaceElevated,
    surfaceMuted: appColors.surfaceMuted,
    surfaceStrong: appColors.surfaceStrong,
    surfaceTint: appColors.surfaceTint,
    surfaceGlass: appColors.surfaceGlass,
    surfaceGlassStrong: appColors.surfaceGlassStrong,
    surfaceGlassTint: appColors.surfaceGlassTint,
    border: appColors.border,
    borderStrong: appColors.borderStrong,
    ink: appColors.label,
    inkSoft: appColors.secondaryLabel,
    inkMuted: appColors.labelMuted,
    inkOnStrong: appColors.labelOnAccent,
    inkOnStrongSoft: appColors.labelOnAccentSoft,
    primary: appColors.accent,
    primaryStrong: appColors.accentPressed,
    primarySoft: appColors.accentSoft,
    secondary: appColors.surfaceTint,
    secondarySoft: appColors.accentSubtle,
    success: appColors.success,
    successStrong: appColors.successPressed,
    successSoft: appColors.successSoft,
    warning: appColors.warning,
    warningSoft: appColors.warningSoft,
    warningStrong: appColors.warningPressed,
    danger: appColors.danger,
    dangerSoft: appColors.dangerSoft,
    dangerStrong: appColors.dangerPressed,
    overlay: appColors.surfaceGlass,
    backdrop: appColors.backdrop,
    highlight: appColors.highlight,
    shadow: appColors.shadow,
    shadowStrong: appColors.shadowStrong,
    primaryShadow: 'rgba(20, 115, 230, 0.20)',
  },
  radius: {
    pill: appTokens.radius.pill,
    card: appTokens.radius.card,
    panel: appTokens.radius.panel,
  },
  tokens: appTokens,
} as const;
